# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          aeth1r js
paginate:       30
baseurl:        "/aeth1r.js.org"
url:            "https://aeth1r.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Aether Lazuli
  url:          http://athelo.net
  email:        aezlo@myself.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/aeth1r/aeth1r.js.org

# Gems
gems:
  - jekyll-paginate
